version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    container_name: app
    environment:
      INDEXER_LOCAL_URL: http://indexer:8000
    depends_on:
      - indexer
      - foundry

  indexer:
    image: ghcr.io/centrifuge/api-v3:latest
    container_name: indexer
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      PONDER_RPC_URL_11155111: http://foundry:8545
      PONDER_RPC_WS_11155111: ws://foundry:8545
      PONDER_RPC_STARTING_BLOCK_11155111: 9325766
      SELECTED_NETWORKS: 11155111
      ALCHEMY_API_KEY: faketoken

  foundry:
    build: .
    container_name: foundry
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
      API_KEY: 18704429-288d-4f55-bda8-8b60f4c53b96
      BLOCK_NUMBER: 9325766
      CHAIN_NUMBER: 11155111
    ports:
      - "8545:8545"
    restart: unless-stopped
