export default [
  'error FileUnrecognizedWhat()',
  'error HoldingNotFound()',
  'error Int128_Overflow()',
  'error NotAuthorized()',
  'error Uint128_Overflow()',
  'error WrongAssetId()',
  'error WrongShareClassId()',
  'error WrongValuation()',
  'event AccountIdSet(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, uint32 accountId)',
  'event Created(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, address valuation)',
  'event Decreased(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, address valuation, uint128 amount, uint128 decreasedValue)',
  'event Deny(address indexed user)',
  'event File(bytes32 indexed what, address addr)',
  'event Increased(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, address valuation, uint128 amount, uint128 increasedValue)',
  'event Rely(address indexed user)',
  'event Updated(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, int128 diffValue)',
  'event ValuationUpdated(uint64 indexed, bytes16 indexed scId, uint128 indexed assetId, address valuation)',
  'function accountId(uint64, bytes16, uint128, uint8 kind) view returns (uint32)',
  'function amount(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint128 amount_)',
  'function create(uint64 poolId, bytes16 scId, uint128 assetId, address valuation_, uint32[] accounts)',
  'function decrease(uint64 poolId, bytes16 scId, uint128 assetId, address valuation_, uint128 amount_) returns (uint128 amountValue)',
  'function deny(address user)',
  'function exists(uint64 poolId, bytes16 scId, uint128 assetId) view returns (bool)',
  'function file(bytes32 what, address data)',
  'function holding(uint64, bytes16, uint128) view returns (uint128 assetAmount, uint128 assetAmountValue, address valuation)',
  'function increase(uint64 poolId, bytes16 scId, uint128 assetId, address valuation_, uint128 amount_) returns (uint128 amountValue)',
  'function poolRegistry() view returns (address)',
  'function rely(address user)',
  'function setAccountId(uint64 poolId, bytes16 scId, uint128 assetId, uint32 accountId_)',
  'function update(uint64 poolId, bytes16 scId, uint128 assetId) returns (int128 diffValue)',
  'function updateValuation(uint64 poolId, bytes16 scId, uint128 assetId, address valuation_)',
  'function valuation(uint64 poolId, bytes16 scId, uint128 assetId) view returns (address)',
  'function value(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint128 value_)',
  'function wards(address) view returns (uint256)',
] as const
