export default [
  'error AccountDoesNotExist()',
  'error AssetNotFound()',
  'error CallFailedWithEmptyRevert()',
  'error FileUnrecognizedParam()',
  'error InvalidPoolId()',
  'error MulDiv_Overflow()',
  'error NoCode()',
  'error NotAuthorized()',
  'error NotManager()',
  'error PoolAlreadyUnlocked()',
  'error SafeTransferEthFailed()',
  'error SafeTransferFailed()',
  'error ShareClassNotFound()',
  'error Uint128_Overflow()',
  'error UnauthorizedSender()',
  'event Deny(address indexed user)',
  'event File(bytes32 what, address addr)',
  'event NotifyAssetPrice(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset)',
  'event NotifyPool(uint16 indexed centrifugeId, uint64 indexed poolId)',
  'event NotifyShareClass(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId)',
  'event NotifySharePrice(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, string name, string symbol)',
  'event NotifySharePrice(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, uint128 poolPerShare)',
  'event Rely(address indexed user)',
  'event UpdateContract(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes32 target, bytes payload)',
  'event UpdateRestriction(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes payload)',
  'event UpdateShareHook(uint16 indexed centrifugeId, uint64 indexed poolId, bytes16 scId, bytes32 hook)',
  'function accounting() view returns (address)',
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt) payable',
  'function approveDeposits(uint64 poolId, bytes16 scId, uint128 depositAssetId, uint32 nowDepositEpochId, uint128 approvedAssetAmount) payable returns (uint128 pendingAssetAmount, uint128 approvedPoolAmount)',
  'function approveRedeems(uint64 poolId, bytes16 scId, uint128 payoutAssetId, uint32 nowRedeemEpochId, uint128 approvedShareAmount) payable returns (uint128 pendingShareAmount)',
  'function cancelDepositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 depositAssetId)',
  'function cancelRedeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 payoutAssetId)',
  'function createAccount(uint64 poolId, uint32 account, bool isDebitNormal) payable',
  'function createHolding(uint64 poolId, bytes16 scId, uint128 assetId, address valuation, uint32 assetAccount, uint32 equityAccount, uint32 lossAccount, uint32 gainAccount) payable',
  'function createLiability(uint64 poolId, bytes16 scId, uint128 assetId, address valuation, uint32 expenseAccount, uint32 liabilityAccount) payable',
  'function createPool(uint64 poolId, address admin, uint128 currency) payable',
  'function decreaseShareIssuance(uint64 poolId, bytes16 scId, uint128 amount)',
  'function deny(address user)',
  'function depositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 depositAssetId, uint128 amount)',
  'function file(bytes32 what, address data)',
  'function gateway() view returns (address)',
  'function holdings() view returns (address)',
  'function hubRegistry() view returns (address)',
  'function increaseShareIssuance(uint64 poolId, bytes16 scId, uint128 amount)',
  'function issueShares(uint64 poolId, bytes16 scId, uint128 depositAssetId, uint32 nowIssueEpochId, uint128 navPoolPerShare) payable returns (uint128 issuedShareAmount, uint128 depositAssetAmount, uint128 depositPoolAmount)',
  'function multicall(bytes[] data) payable',
  'function notifyAssetPrice(uint64 poolId, bytes16 scId, uint128 assetId) payable',
  'function notifyDeposit(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint32 maxClaims) payable',
  'function notifyPool(uint64 poolId, uint16 centrifugeId) payable',
  'function notifyRedeem(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint32 maxClaims) payable',
  'function notifyShareClass(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes32 hook) payable',
  'function notifyShareMetadata(uint64 poolId, bytes16 scId, uint16 centrifugeId) payable',
  'function notifySharePrice(uint64 poolId, bytes16 scId, uint16 centrifugeId) payable',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function redeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 payoutAssetId, uint128 amount)',
  'function registerAsset(uint128 assetId, uint8 decimals)',
  'function rely(address user)',
  'function revokeShares(uint64 poolId, bytes16 scId, uint128 payoutAssetId, uint32 nowRevokeEpochId, uint128 navPoolPerShare) payable returns (uint128 revokedShareAmount, uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'function sender() view returns (address)',
  'function setAccountMetadata(uint64 poolId, uint32 account, bytes metadata) payable',
  'function setHoldingAccountId(uint64 poolId, bytes16 scId, uint128 assetId, uint8 kind, uint32 accountId) payable',
  'function setPoolMetadata(uint64 poolId, bytes metadata) payable',
  'function setQueue(uint16 centrifugeId, uint64 poolId, bytes16 scId, bool enabled) payable',
  'function shareClassManager() view returns (address)',
  'function triggerIssueShares(uint16 centrifugeId, uint64 poolId, bytes16 scId, address who, uint128 shares) payable',
  'function triggerSubmitQueuedAssets(uint64 poolId, bytes16 scId, uint128 assetId) payable',
  'function triggerSubmitQueuedShares(uint16 centrifugeId, uint64 poolId, bytes16 scId) payable',
  'function updateContract(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes32 target, bytes payload) payable',
  'function updateHoldingAmount(uint64 poolId, bytes16 scId, uint128 assetId, uint128 amount, uint128 pricePoolPerAsset, bool isIncrease)',
  'function updateHoldingValuation(uint64 poolId, bytes16 scId, uint128 assetId, address valuation) payable',
  'function updateHoldingValue(uint64 poolId, bytes16 scId, uint128 assetId) payable',
  'function updateJournal(uint64 poolId, (uint128 value, uint32 accountId)[] debits, (uint128 value, uint32 accountId)[] credits)',
  'function updateManager(uint64 poolId, address who, bool canManage) payable',
  'function updatePricePerShare(uint64 poolId, bytes16 scId, uint128 navPoolPerShare) payable',
  'function updateRestriction(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes payload) payable',
  'function updateShareClassMetadata(uint64 poolId, bytes16 scId, string name, string symbol) payable',
  'function updateShareHook(uint64 poolId, bytes16 scId, uint16 centrifugeId, bytes32 hook) payable',
  'function wards(address) view returns (uint256)',
] as const
