export default [
  'error AssetNotFound()',
  'error CallFailedWithEmptyRevert()',
  'error FileUnrecognizedWhat()',
  'error MulDiv_Overflow()',
  'error NoCode()',
  'error NotAuthorized()',
  'error NotAuthorizedAdmin()',
  'error PoolAlreadyUnlocked()',
  'error PoolLocked()',
  'error SafeTransferEthFailed()',
  'error SafeTransferFailed()',
  'error ShareClassNotFound()',
  'error Uint128_Overflow()',
  'error UnauthorizedSender()',
  'event Deny(address indexed user)',
  'event File(bytes32 what, address addr)',
  'event Rely(address indexed user)',
  'function accounting() view returns (address)',
  'function addCredit(uint64 poolId, uint32 account, uint128 amount) payable',
  'function addDebit(uint64 poolId, uint32 account, uint128 amount) payable',
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt, bytes data) payable',
  'function allowPoolAdmin(uint64 poolId, address account, bool allow) payable',
  'function approveDeposits(uint64 poolId, bytes16 scId, uint128 paymentAssetId, uint128 maxApproval, address valuation) payable',
  'function approveRedeems(uint64 poolId, bytes16 scId, uint128 payoutAssetId, uint128 maxApproval) payable',
  'function cancelDepositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 depositAssetId)',
  'function cancelRedeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 payoutAssetId)',
  'function claimDeposit(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor) payable',
  'function claimRedeem(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor) payable',
  'function createAccount(uint64 poolId, uint32 account, bool isDebitNormal) payable',
  'function createHolding(uint64 poolId, bytes16 scId, uint128 assetId, address valuation, bool isLiability, uint24 prefix) payable',
  'function createPool(address admin, uint128 currency) payable returns (uint64 poolId)',
  'function decreaseShareIssuance(uint64 poolId, bytes16 scId, uint128 pricePerShare, uint128 amount)',
  'function deny(address user)',
  'function depositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 depositAssetId, uint128 amount)',
  'function file(bytes32 what, address data)',
  'function gateway() view returns (address)',
  'function holdings() view returns (address)',
  'function hubRegistry() view returns (address)',
  'function increaseShareIssuance(uint64 poolId, bytes16 scId, uint128 pricePerShare, uint128 amount)',
  'function issueShares(uint64 poolId, bytes16 scId, uint128 depositAssetId, uint128 navPerShare) payable',
  'function multicall(bytes[] data) payable',
  'function notifyAssetPrice(uint64 poolId, bytes16 scId, uint128 assetId) payable',
  'function notifyPool(uint64 poolId, uint16 centrifugeId) payable',
  'function notifyShareClass(uint64 poolId, uint16 centrifugeId, bytes16 scId, bytes32 hook) payable',
  'function notifySharePrice(uint64 poolId, uint16 centrifugeId, bytes16 scId) payable',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function redeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 payoutAssetId, uint128 amount)',
  'function registerAsset(uint128 assetId, uint8 decimals)',
  'function rely(address user)',
  'function revokeShares(uint64 poolId, bytes16 scId, uint128 payoutAssetId, uint128 navPerShare, address valuation) payable',
  'function sender() view returns (address)',
  'function setAccountMetadata(uint64 poolId, uint32 account, bytes metadata) payable',
  'function setHoldingAccountId(uint64 poolId, bytes16 scId, uint128 assetId, uint32 accountId) payable',
  'function setPoolMetadata(uint64 poolId, bytes metadata) payable',
  'function shareClassManager() view returns (address)',
  'function transientValuation() view returns (address)',
  'function updateContract(uint64 poolId, uint16 centrifugeId, bytes16 scId, bytes32 target, bytes payload) payable',
  'function updateHoldingAmount(uint64 poolId, bytes16 scId, uint128 assetId, uint128 amount, uint128 pricePoolPerAsset, bool isIncrease, (uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits)',
  'function updateHoldingValuation(uint64 poolId, bytes16 scId, uint128 assetId, address valuation) payable',
  'function updateHoldingValue(uint64 poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset)',
  'function updateJournal(uint64 poolId, (uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits)',
  'function updatePricePoolPerShare(uint64 poolId, bytes16 scId, uint128 navPerShare, bytes data) payable',
  'function updateRestriction(uint64 poolId, uint16 centrifugeId, bytes16 scId, bytes payload) payable',
  'function wards(address) view returns (uint256)',
] as const
