export default [
  'error AssetAlreadyRegistered()',
  'error AssetNotFound()',
  'error EmptyAdmin()',
  'error EmptyCurrency()',
  'error EmptyShareClassManager()',
  'error NonExistingPool(uint64 id)',
  'error NotAuthorized()',
  'error PoolAlreadyRegistered()',
  'error Uint128_Overflow()',
  'event Deny(address indexed user)',
  'event NewAsset(uint128 indexed assetId, uint8 decimals)',
  'event NewPool(uint64 poolId, address indexed admin, uint128 indexed currency)',
  'event Rely(address indexed user)',
  'event SetMetadata(uint64 indexed poolId, bytes metadata)',
  'event UpdateAdmin(uint64 indexed poolId, address indexed admin, bool canManage)',
  'event UpdateCurrency(uint64 indexed poolId, uint128 currency)',
  'event UpdateDependency(bytes32 indexed what, address dependency)',
  'function currency(uint64) view returns (uint128)',
  'function decimals(uint256 asset_) view returns (uint8 decimals_)',
  'function decimals(uint64 poolId) view returns (uint8 decimals_)',
  'function deny(address user)',
  'function dependency(bytes32) view returns (address)',
  'function exists(uint64 poolId) view returns (bool)',
  'function isAdmin(uint64, address) view returns (bool)',
  'function isRegistered(uint128 assetId) view returns (bool)',
  'function latestId() view returns (uint48)',
  'function metadata(uint64) view returns (bytes)',
  'function registerAsset(uint128 assetId, uint8 decimals_)',
  'function registerPool(address admin_, uint16 centrifugeId, uint128 currency_) returns (uint64 poolId)',
  'function rely(address user)',
  'function setMetadata(uint64 poolId, bytes metadata_)',
  'function updateAdmin(uint64 poolId, address admin_, bool canManage)',
  'function updateCurrency(uint64 poolId, uint128 currency_)',
  'function updateDependency(bytes32 what, address dependency_)',
  'function wards(address) view returns (uint256)',
] as const
