export default [
  'error FileUnrecognizedParam()',
  'error NotAuthorized()',
  'error Uint64_Overflow()',
  'event Deny(address indexed user)',
  'event File(bytes32 indexed what, address addr)',
  'event Rely(address indexed user)',
  'function balanceSheetManager() view returns (address)',
  'function deny(address user)',
  'function file(bytes32 what, address data)',
  'function gateway() view returns (address)',
  'function investmentManager() view returns (address)',
  'function localCentrifugeId() view returns (uint16)',
  'function poolManager() view returns (address)',
  'function poolRouter() view returns (address)',
  'function rely(address user)',
  'function sendCancelDepositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId)',
  'function sendCancelRedeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId)',
  'function sendDecreaseHolding(uint64 poolId, bytes16 scId, uint128 assetId, address receiver, uint128 amount, uint128 pricePerUnit, uint256 timestamp, (uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits)',
  'function sendDepositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId, uint128 amount)',
  'function sendFulfilledCancelDepositRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 cancelledAmount)',
  'function sendFulfilledCancelRedeemRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 cancelledShares)',
  'function sendFulfilledDepositRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 assetAmount, uint128 shareAmount)',
  'function sendFulfilledRedeemRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 assetAmount, uint128 shareAmount)',
  'function sendIncreaseHolding(uint64 poolId, bytes16 scId, uint128 assetId, address provider, uint128 amount, uint128 pricePerUnit, uint256 timestamp, (uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits)',
  'function sendIssueShares(uint64 poolId, bytes16 scId, address receiver, uint128 pricePerShare, uint128 shares, uint256 timestamp)',
  'function sendJournalEntry(uint64 poolId, bytes16 scId, (uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits)',
  'function sendNotifyPool(uint16 chainId, uint64 poolId)',
  'function sendNotifyShareClass(uint16 chainId, uint64 poolId, bytes16 scId, string name, string symbol, uint8 decimals, bytes32 salt, bytes32 hook)',
  'function sendNotifySharePrice(uint16 chainId, uint64 poolId, bytes16 scId, uint128 assetId, uint128 sharePrice)',
  'function sendRedeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId, uint128 amount)',
  'function sendRegisterAsset(uint16 chainId, uint128 assetId, string name, string symbol, uint8 decimals)',
  'function sendRevokeShares(uint64 poolId, bytes16 scId, address provider, uint128 pricePerShare, uint128 shares, uint256 timestamp)',
  'function sendTransferShares(uint16 chainId, uint64 poolId, bytes16 scId, bytes32 recipient, uint128 amount)',
  'function sendUpdateContract(uint16 chainId, uint64 poolId, bytes16 scId, bytes32 target, bytes payload)',
  'function sendUpdateHoldingValue(uint64 poolId, bytes16 scId, uint128 assetId, uint128 pricePerUnit, uint256 timestamp)',
  'function wards(address) view returns (uint256)',
] as const
