export default [
  // 'error FileUnrecognizedParam()',
  // 'error NotAuthorized()',
  // 'error Uint64_Overflow()',
  // 'event Deny(address indexed user)',
  // 'event File(bytes32 indexed what, address addr)',
  // 'event Rely(address indexed user)',
  // 'function balanceSheet() view returns (address)',
  // 'function deny(address user)',
  // 'function estimate(uint16 centrifugeId, bytes payload) view returns (uint256 amount)',
  // 'function file(bytes32 what, address data)',
  // 'function gateway() view returns (address)',
  // 'function hub() view returns (address)',
  // 'function investmentManager() view returns (address)',
  'function localCentrifugeId() view returns (uint16)',
  // 'function spoke() view returns (address)',
  // 'function rely(address user)',
  // 'function root() view returns (address)',
  // 'function sendApprovedDeposits(uint64 poolId, bytes16 scId, uint128 assetId, uint128 assetAmount)',
  // 'function sendCancelDepositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId)',
  // 'function sendCancelRedeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId)',
  // 'function sendCancelUpgrade(uint16 centrifugeId, bytes32 target)',
  // 'function sendDepositRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId, uint128 amount)',
  // 'function sendDisputeMessageRecovery(uint16 centrifugeId, uint16 adapterCentrifugeId, bytes32 adapter, bytes32 hash)',
  // 'function sendFulfilledCancelDepositRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 cancelledAmount)',
  // 'function sendFulfilledCancelRedeemRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 cancelledShares)',
  // 'function sendFulfilledDepositRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 assetAmount, uint128 shareAmount)',
  // 'function sendFulfilledRedeemRequest(uint64 poolId, bytes16 scId, uint128 assetId, bytes32 investor, uint128 assetAmount, uint128 shareAmount)',
  // 'function sendInitiateMessageRecovery(uint16 centrifugeId, uint16 adapterCentrifugeId, bytes32 adapter, bytes32 hash)',
  // 'function sendJournalEntry(uint64 poolId, (uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits)',
  // 'function sendNotifyPool(uint16 centrifugeId, uint64 poolId)',
  // 'function sendNotifyPricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId, uint128 price)',
  // 'function sendNotifyPricePoolPerShare(uint16 chainId, uint64 poolId, bytes16 scId, uint128 sharePrice)',
  // 'function sendNotifyShareClass(uint16 centrifugeId, uint64 poolId, bytes16 scId, string name, string symbol, uint8 decimals, bytes32 salt, bytes32 hook)',
  // 'function sendRecoverTokens(uint16 centrifugeId, bytes32 target, bytes32 token, uint256 tokenId, bytes32 to, uint256 amount)',
  // 'function sendRedeemRequest(uint64 poolId, bytes16 scId, bytes32 investor, uint128 assetId, uint128 amount)',
  // 'function sendRegisterAsset(uint16 centrifugeId, uint128 assetId, uint8 decimals)',
  // 'function sendRevokedShares(uint64 poolId, bytes16 scId, uint128 assetId, uint128 assetAmount)',
  // 'function sendScheduleUpgrade(uint16 centrifugeId, bytes32 target)',
  // 'function sendTransferShares(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount)',
  // 'function sendUpdateContract(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 target, bytes payload)',
  // 'function sendUpdateHoldingAmount(uint64 poolId, bytes16 scId, uint128 assetId, address provider, uint128 amount, uint128 pricePoolPerAsset, bool isIncrease, ((uint128 amount, uint32 accountId)[] debits, (uint128 amount, uint32 accountId)[] credits) meta)',
  // 'function sendUpdateHoldingValue(uint64 poolId, bytes16 scId, uint128 assetId, uint128 pricePoolPerAsset)',
  // 'function sendUpdateRestriction(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes payload)',
  // 'function sendUpdateShares(uint64 poolId, bytes16 scId, address receiver, uint128 pricePoolPerShare, uint128 shares, bool isIssuance)',
  // 'function tokenRecoverer() view returns (address)',
  // 'function wards(address) view returns (uint256)',
] as const
