export default [
  'error AssetMissingDecimals()',
  'error CannotSetOlderPrice()',
  'error FileUnrecognizedParam()',
  'error InvalidFactory()',
  'error InvalidHook()',
  'error InvalidPool()',
  'error InvalidPrice()',
  'error MalformedVaultUpdateMessage()',
  'error MulDiv_Overflow()',
  'error NoCode()',
  'error NotAuthorized()',
  'error OldHook()',
  'error OldMetadata()',
  'error PoolAlreadyAdded()',
  'error SafeTransferEthFailed()',
  'error SafeTransferFailed()',
  'error ShareClassAlreadyRegistered()',
  'error ShareTokenDoesNotExist()',
  'error TooFewDecimals()',
  'error TooManyDecimals()',
  'error Uint128_Overflow()',
  'error UnknownAsset()',
  'error UnknownMessageType()',
  'error UnknownToken()',
  'error UnknownUpdateContractType()',
  'error UnknownVault()',
  'event AddPool(uint64 indexed poolId)',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, address token)',
  'event Deny(address indexed user)',
  'event DeployVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address factory, address vault)',
  'event File(bytes32 indexed what, address data)',
  'event File(bytes32 indexed what, address factory, bool status)',
  'event LinkVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address vault)',
  'event PriceUpdate(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, uint256 price, uint64 computedAt)',
  'event PriceUpdate(uint64 indexed poolId, bytes16 indexed scId, uint256 price, uint64 computedAt)',
  'event RegisterAsset(uint128 indexed assetId, address indexed asset, uint256 indexed tokenId, string name, string symbol, uint8 decimals)',
  'event Rely(address indexed user)',
  'event TransferShares(uint64 centrifugeId, uint64 indexed poolId, bytes16 indexed scId, address indexed sender, bytes32 destinationAddress, uint128 amount)',
  'event UnlinkVault(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, address vault)',
  'event UpdateContract(uint64 indexed poolId, bytes16 indexed scId, address target, bytes payload)',
  'event UpdateMaxAssetPriceAge(uint64 indexed poolId, bytes16 indexed scId, address indexed asset, uint256 tokenId, uint64 maxPriceAge)',
  'event UpdateMaxSharePriceAge(uint64 indexed poolId, bytes16 indexed scId, uint64 maxPriceAge)',
  'function addPool(uint64 poolId)',
  'function addShareClass(uint64 poolId, bytes16 scId, string name, string symbol, uint8 decimals, bytes32 salt, address hook) returns (address)',
  'function assetToId(address asset, uint256 tokenId) view returns (uint128 assetId)',
  'function balanceSheet() view returns (address)',
  'function deny(address user)',
  'function deployVault(uint64 poolId, bytes16 scId, uint128 assetId, address factory) returns (address)',
  'function escrow() view returns (address)',
  'function file(bytes32 what, address factory, bool status)',
  'function file(bytes32 what, address data)',
  'function handleTransferShares(uint64 poolId, bytes16 scId, address destinationAddress, uint128 amount)',
  'function idToAsset(uint128 assetId) view returns (address asset, uint256 tokenId)',
  'function isLinked(uint64, bytes16, address, address vault) view returns (bool)',
  'function isPoolActive(uint64 poolId) view returns (bool)',
  'function linkVault(uint64 poolId, bytes16 scId, uint128 assetId, address vault)',
  'function pools(uint64 poolId) view returns (uint256 createdAt)',
  'function priceAssetPerShare(uint64 poolId, bytes16 scId, uint128 assetId, bool checkValidity) view returns (uint128 price, uint64 computedAt)',
  'function pricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId, bool checkValidity) view returns (uint128 price, uint64 computedAt)',
  'function pricePoolPerShare(uint64 poolId, bytes16 scId, bool checkValidity) view returns (uint128 price, uint64 computedAt)',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function registerAsset(uint16 centrifugeId, address asset, uint256 tokenId) returns (uint128 assetId)',
  'function rely(address user)',
  'function sender() view returns (address)',
  'function shareToken(uint64 poolId, bytes16 scId) view returns (address)',
  'function tokenFactory() view returns (address)',
  'function transferShares(uint16 centrifugeId, uint64 poolId, bytes16 scId, bytes32 receiver, uint128 amount)',
  'function unlinkVault(uint64 poolId, bytes16 scId, uint128 assetId, address vault)',
  'function update(uint64 poolId, bytes16 scId, bytes payload)',
  'function updateContract(uint64 poolId, bytes16 scId, address target, bytes update_)',
  'function updatePricePoolPerAsset(uint64 poolId, bytes16 scId, uint128 assetId, uint128 poolPerAsset_, uint64 computedAt)',
  'function updatePricePoolPerShare(uint64 poolId, bytes16 scId, uint128 price, uint64 computedAt)',
  'function updateRestriction(uint64 poolId, bytes16 scId, bytes update_)',
  'function updateShareHook(uint64 poolId, bytes16 scId, address hook)',
  'function updateShareMetadata(uint64 poolId, bytes16 scId, string name, string symbol)',
  'function vaultDetails(address vault) view returns ((uint128 assetId, address asset, uint256 tokenId, bool isWrapper, bool isLinked) details)',
  'function vaultFactory(address factory) view returns (bool)',
  'function wards(address) view returns (uint256)',
] as const
