export default [
  'constructor(address deployer)',
  'error EmptyAdmin()',
  'error EmptyCurrency()',
  'error EmptyShareClassManager()',
  'error NonExistingPool(uint64 id)',
  'error NotAuthorized()',
  'event Deny(address indexed user)',
  'event NewPool(uint64 poolId, address indexed admin, address indexed shareClassManager, uint128 indexed currency)',
  'event Rely(address indexed user)',
  'event SetMetadata(uint64 indexed poolId, bytes metadata)',
  'event UpdatedAdmin(uint64 indexed poolId, address indexed admin, bool canManage)',
  'event UpdatedCurrency(uint64 indexed poolId, uint128 currency)',
  'event UpdatedShareClassManager(uint64 indexed poolId, address indexed shareClassManager)',
  'function currency(uint64) view returns (uint128)',
  'function deny(address user)',
  'function exists(uint64 poolId) view returns (bool)',
  'function isAdmin(uint64, address) view returns (bool)',
  'function latestId() view returns (uint32)',
  'function metadata(uint64) view returns (bytes)',
  'function registerPool(address admin_, uint16 centrifugeChainId, uint128 currency_, address shareClassManager_) returns (uint64 poolId)',
  'function rely(address user)',
  'function setMetadata(uint64 poolId, bytes metadata_)',
  'function shareClassManager(uint64) view returns (address)',
  'function updateAdmin(uint64 poolId, address admin_, bool canManage)',
  'function updateCurrency(uint64 poolId, uint128 currency_)',
  'function updateShareClassManager(uint64 poolId, address shareClassManager_)',
  'function wards(address) view returns (uint256)',
] as const
