export default [
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt) returns (bytes16 scId_)',
  'function allowForceDepositCancel(bytes16 scId, uint128 depositAssetId, bytes32 investor) view returns (bool cancelled)',
  'function allowForceRedeemCancel(bytes16 scId, uint128 payoutAssetId, bytes32 investor) view returns (bool cancelled)',
  'function approveDeposits(uint64 poolId, bytes16 scId_, uint128 depositAssetId, uint32 nowDepositEpochId, uint128 approvedAssetAmount, uint128 pricePoolPerAsset) returns (uint128 pendingAssetAmount, uint128 approvedPoolAmount)',
  'function approveRedeems(uint64 poolId, bytes16 scId_, uint128 payoutAssetId, uint32 nowRedeemEpochId, uint128 approvedShareAmount, uint128 pricePoolPerAsset) returns (uint128 pendingShareAmount)',
  'function cancelDepositRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) returns (uint128 cancelledAssetAmount)',
  'function cancelRedeemRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 cancelledShareAmount)',
  'function claimDeposit(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) returns (uint128 payoutShareAmount, uint128 paymentAssetAmount, uint128 cancelledAssetAmount, bool canClaimAgain)',
  'function claimRedeem(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 payoutAssetAmount, uint128 paymentShareAmount, uint128 cancelledShareAmount, bool canClaimAgain)',
  'function deny(address user)',
  'function depositRequest(bytes16 scId, uint128 depositAssetId, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function epochId(bytes16 scId, uint128 assetId) view returns (uint32 deposit, uint32 redeem, uint32 issue, uint32 revoke)',
  'function epochInvestAmounts(bytes16 scId, uint128 assetId, uint32 epochId_) view returns (uint128 pendingAssetAmount, uint128 approvedAssetAmount, uint128 approvedPoolAmount, uint128 pricePoolPerAsset, uint128 navPoolPerShare, uint64 issuedAt)',
  'function epochRedeemAmounts(bytes16 scId, uint128 assetId, uint32 epochId_) view returns (uint128 pendingShareAmount, uint128 approvedShareAmount, uint128 payoutAssetAmount, uint128 pricePoolPerAsset, uint128 navPoolPerShare, uint64 revokedAt)',
  'function exists(uint64 poolId, bytes16 scId_) view returns (bool)',
  'function forceCancelDepositRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) returns (uint128 cancelledAssetAmount)',
  'function forceCancelRedeemRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 cancelledShareAmount)',
  'function hubRegistry() view returns (address)',
  'function issuance(bytes16 scId, uint16 centrifugeId) view returns (uint128)',
  'function issueShares(uint64 poolId, bytes16 scId_, uint128 depositAssetId, uint32 nowIssueEpochId, uint128 navPoolPerShare) returns (uint128 issuedShareAmount, uint128 depositAssetAmount, uint128 depositPoolAmount)',
  'function maxDepositClaims(bytes16 scId_, bytes32 investor, uint128 depositAssetId) view returns (uint32)',
  'function maxRedeemClaims(bytes16 scId_, bytes32 investor, uint128 payoutAssetId) view returns (uint32)',
  'function metadata(bytes16 scId) view returns (string name, string symbol, bytes32 salt)',
  'function metrics(bytes16 scId) view returns (uint128 totalIssuance, uint128 navPerShare)',
  'function nowDepositEpoch(bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function nowIssueEpoch(bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function nowRedeemEpoch(bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function nowRevokeEpoch(bytes16 scId_, uint128 depositAssetId) view returns (uint32)',
  'function pendingDeposit(bytes16 scId, uint128 depositAssetId) view returns (uint128 pending)',
  'function pendingRedeem(bytes16 scId, uint128 payoutAssetId) view returns (uint128 pending)',
  'function previewNextShareClassId(uint64 poolId) view returns (bytes16 scId)',
  'function previewShareClassId(uint64 poolId, uint32 index) pure returns (bytes16 scId)',
  'function queuedDepositRequest(bytes16 scId, uint128 depositAssetId, bytes32 investor) view returns (bool isCancelling, uint128 amount)',
  'function queuedRedeemRequest(bytes16 scId, uint128 payoutAssetId, bytes32 investor) view returns (bool isCancelling, uint128 amount)',
  'function redeemRequest(bytes16 scId, uint128 payoutAssetId, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function rely(address user)',
  'function requestDeposit(uint64 poolId, bytes16 scId_, uint128 amount, bytes32 investor, uint128 depositAssetId)',
  'function requestRedeem(uint64 poolId, bytes16 scId_, uint128 amount, bytes32 investor, uint128 payoutAssetId)',
  'function revokeShares(uint64 poolId, bytes16 scId_, uint128 payoutAssetId, uint32 nowRevokeEpochId, uint128 navPoolPerShare) returns (uint128 revokedShareAmount, uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'function salts(bytes32 salt) view returns (bool)',
  'function shareClassCount(uint64 poolId) view returns (uint32)',
  'function shareClassIds(uint64 poolId, bytes16) view returns (bool)',
  'function updateMetadata(uint64 poolId, bytes16 scId_, string name, string symbol)',
  'function updateSharePrice(uint64 poolId, bytes16 scId_, uint128 navPoolPerShare)',
  'function updateShares(uint16 centrifugeId, uint64 poolId, bytes16 scId_, uint128 amount, bool isIssuance)',
  'function wards(address) view returns (uint256)',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index, string name, string symbol, bytes32 salt)',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index)',
  'event ApproveDeposits(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed depositAssetId, uint32 epoch, uint128 approvedPoolAmount, uint128 approvedAssetAmount, uint128 pendingAssetAmount)',
  'event ApproveRedeems(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed payoutAssetId, uint32 epoch, uint128 approvedShareAmount, uint128 pendingShareAmount)',
  'event ClaimDeposit(uint64 indexed poolId, bytes16 indexed scId, uint32 epoch, bytes32 investor, uint128 indexed depositAssetId, uint128 paymentAssetAmount, uint128 pendingAssetAmount, uint128 claimedShareAmount, uint64 issuedAt)',
  'event ClaimRedeem(uint64 indexed poolId, bytes16 indexed scId, uint32 epoch, bytes32 investor, uint128 indexed payoutAssetId, uint128 paymentShareAmount, uint128 pendingShareAmount, uint128 claimedAssetAmount, uint64 revokedAt)',
  'event Deny(address indexed user)',
  'event IssueShares(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed depositAssetId, uint32 epoch, uint128 navPoolPerShare, uint128 navAssetPerShare, uint128 issuedShareAmount)',
  'event Rely(address indexed user)',
  'event RemoteIssueShares(uint16 centrifugeId, uint64 indexed poolId, bytes16 indexed scId, uint128 issuedShareAmount)',
  'event RemoteRevokeShares(uint16 centrifugeId, uint64 indexed poolId, bytes16 indexed scId, uint128 revokedAssetAmount)',
  'event RevokeShares(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed payoutAssetId, uint32 epoch, uint128 navPoolPerShare, uint128 navAssetPerShare, uint128 revokedShareAmount, uint128 revokedAssetAmount, uint128 revokedPoolAmount)',
  'event UpdateDepositRequest(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed depositAssetId, uint32 epoch, bytes32 investor, uint128 pendingUserAssetAmount, uint128 pendingTotalAssetAmount, uint128 queuedUserAssetAmount, bool pendingCancellation)',
  'event UpdateMetadata(uint64 indexed poolId, bytes16 indexed scId, string name, string symbol)',
  'event UpdateRedeemRequest(uint64 indexed poolId, bytes16 indexed scId, uint128 indexed payoutAssetId, uint32 epoch, bytes32 investor, uint128 pendingUserShareAmount, uint128 pendingTotalShareAmount, uint128 queuedUserShareAmount, bool pendingCancellation)',
  'event UpdateShareClass(uint64 indexed poolId, bytes16 indexed scId, uint128 navPoolPerShare)',
  'error AlreadyIssued()',
  'error AlreadyUsedSalt()',
  'error ApprovalRequired()',
  'error CancellationInitializationRequired()',
  'error CancellationQueued()',
  'error DecreaseMoreThanIssued()',
  'error EpochNotFound()',
  'error EpochNotInSequence(uint32 providedEpoch, uint32 nowEpoch)',
  'error InsufficientPending()',
  'error InvalidMetadataName()',
  'error InvalidMetadataSize()',
  'error InvalidMetadataSymbol()',
  'error InvalidSalt()',
  'error IssuanceRequired()',
  'error MulDiv_Overflow()',
  'error NoOrderFound()',
  'error NotAuthorized()',
  'error PoolMissing()',
  'error RevocationRequired()',
  'error RevokeMoreThanIssued()',
  'error ShareClassNotFound()',
  'error Uint128_Overflow()',
  'error Uint64_Overflow()',
  'error ZeroApprovalAmount()',
] as const
