export default [
  'error AlreadyApproved()',
  'error AlreadyUsedSalt()',
  'error ApprovalRequired()',
  'error ClaimDepositRequired()',
  'error ClaimRedeemRequired()',
  'error EpochNotFound()',
  'error InvalidMetadataName()',
  'error InvalidMetadataSize()',
  'error InvalidMetadataSymbol()',
  'error InvalidSalt()',
  'error MaxShareClassNumberExceeded(uint8 numberOfShareClasses)',
  'error MulDiv_Overflow()',
  'error NotAuthorized()',
  'error PoolMissing()',
  'error RevokeMoreThanIssued()',
  'error ShareClassNotFound()',
  'error Uint128_Overflow()',
  'error UnrecognizedFileParam()',
  'error ZeroApprovalAmount()',
  'event AddedShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index, string name, string symbol, bytes32 salt)',
  'event AddedShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index)',
  'event ApprovedDeposits(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 assetId, uint128 approvedPoolAmount, uint128 approvedAssetAmount, uint128 pendingAssetAmount)',
  'event ApprovedRedeems(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 assetId, uint128 approvedShareClassAmount, uint128 pendingShareClassAmount)',
  'event ClaimedDeposit(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, bytes32 investor, uint128 assetId, uint128 approvedAssetAmount, uint128 pendingAssetAmount, uint128 claimedShareAmount)',
  'event ClaimedRedeem(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, bytes32 investor, uint128 assetId, uint128 approvedShareClassAmount, uint128 pendingShareClassAmount, uint128 claimedAssetAmount)',
  'event Deny(address indexed user)',
  'event File(bytes32 what, address who)',
  'event IssuedShares(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 navPerShare, uint128 nav, uint128 issuedShareAmount)',
  'event NewEpoch(uint64 poolId, uint32 newIndex)',
  'event Rely(address indexed user)',
  'event RevokedShares(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 navPerShare, uint128 nav, uint128 revokedShareAmount, uint128 revokedAssetAmount)',
  'event UpdatedDepositRequest(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, bytes32 investor, uint128 assetId, uint128 updatedAmountUser, uint128 updatedAmountTotal)',
  'event UpdatedMetadata(uint64 indexed poolId, bytes16 indexed scId, string name, string symbol, bytes32 salt)',
  'event UpdatedNav(uint64 indexed poolId, bytes16 indexed scId, uint128 newAmount)',
  'event UpdatedRedeemRequest(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, bytes32 investor, uint128 payoutAssetId, uint128 updatedAmountUser, uint128 updatedAmountTotal)',
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt, bytes) returns (bytes16 shareClassId_)',
  'function approveDeposits(uint64 poolId, bytes16 shareClassId_, uint128 maxApproval, uint128 paymentAssetId, address valuation) returns (uint128 approvedAssetAmount, uint128 approvedPoolAmount)',
  'function approveRedeems(uint64 poolId, bytes16 shareClassId_, uint128 maxApproval, uint128 payoutAssetId) returns (uint128 approvedShareAmount, uint128 pendingShareAmount)',
  'function cancelDepositRequest(uint64 poolId, bytes16 shareClassId_, bytes32 investor, uint128 depositAssetId) returns (uint128 cancelledAssetAmount)',
  'function cancelRedeemRequest(uint64 poolId, bytes16 shareClassId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 cancelledShareAmount)',
  'function claimDeposit(uint64 poolId, bytes16 shareClassId_, bytes32 investor, uint128 depositAssetId) returns (uint128 payoutShareAmount, uint128 paymentAssetAmount)',
  'function claimDepositUntilEpoch(uint64 poolId, bytes16 shareClassId_, bytes32 investor, uint128 depositAssetId, uint32 endEpochId) returns (uint128 payoutShareAmount, uint128 paymentAssetAmount)',
  'function claimRedeem(uint64 poolId, bytes16 shareClassId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 payoutAssetAmount, uint128 paymentShareAmount)',
  'function claimRedeemUntilEpoch(uint64 poolId, bytes16 shareClassId_, bytes32 investor, uint128 payoutAssetId, uint32 endEpochId) returns (uint128 payoutAssetAmount, uint128 paymentShareAmount)',
  'function deny(address user)',
  'function depositRequest(bytes16 scId, uint128 paymentAssetId, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function epochAmounts(bytes16 scId, uint128 assetId, uint32 epochId_) view returns (uint128 depositPending, uint128 depositApproved, uint128 depositPool, uint128 depositShares, uint128 redeemPending, uint128 redeemApproved, uint128 redeemAssets)',
  'function epochId(uint64 poolId) view returns (uint32)',
  'function epochPointers(bytes16 scId, uint128 assetId) view returns (uint32 latestDepositApproval, uint32 latestRedeemApproval, uint32 latestIssuance, uint32 latestRevocation)',
  'function exists(uint64 poolId, bytes16 shareClassId_) view returns (bool)',
  'function file(bytes32 what, address data)',
  'function issueShares(uint64 poolId, bytes16 shareClassId_, uint128 depositAssetId, uint128 navPerShare)',
  'function issueSharesUntilEpoch(uint64 poolId, bytes16 shareClassId_, uint128 depositAssetId, uint128 navPerShare, uint32 endEpochId)',
  'function metadata(bytes16 scId) view returns (string name, string symbol, bytes32 salt)',
  'function metrics(bytes16 scId) view returns (uint128 totalIssuance, uint128 navPerShare)',
  'function pendingDeposit(bytes16 scId, uint128 paymentAssetId) view returns (uint128 pending)',
  'function pendingRedeem(bytes16 scId, uint128 payoutAssetId) view returns (uint128 pending)',
  'function poolRegistry() view returns (address)',
  'function previewNextShareClassId(uint64 poolId) view returns (bytes16 scId)',
  'function previewShareClassId(uint64 poolId, uint32 index) pure returns (bytes16 scId)',
  'function redeemRequest(bytes16 scId, uint128 payoutAssetId, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function rely(address user)',
  'function requestDeposit(uint64 poolId, bytes16 shareClassId_, uint128 amount, bytes32 investor, uint128 depositAssetId)',
  'function requestRedeem(uint64 poolId, bytes16 shareClassId_, uint128 amount, bytes32 investor, uint128 payoutAssetId)',
  'function revokeShares(uint64 poolId, bytes16 shareClassId_, uint128 payoutAssetId, uint128 navPerShare, address valuation) returns (uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'function revokeSharesUntilEpoch(uint64 poolId, bytes16 shareClassId_, uint128 payoutAssetId, uint128 navPerShare, address valuation, uint32 endEpochId) returns (uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'function salts(bytes32 salt) view returns (bool)',
  'function shareClassCount(uint64 poolId) view returns (uint32)',
  'function shareClassIds(uint64 poolId, bytes16) view returns (bool)',
  'function update(uint64, bytes) pure',
  'function updateMetadata(uint64 poolId, bytes16 shareClassId_, string name, string symbol, bytes32 salt, bytes)',
  'function updateShareClassNav(uint64 poolId, bytes16 shareClassId_) view returns (uint128, uint128)',
  'function wards(address) view returns (uint256)',
] as const
