export default [
  'error AlreadyApproved()',
  'error AlreadyUsedSalt()',
  'error ApprovalRequired()',
  'error CancellationQueued()',
  'error DecreaseMoreThanIssued()',
  'error EpochNotFound()',
  'error InvalidMetadataName()',
  'error InvalidMetadataSize()',
  'error InvalidMetadataSymbol()',
  'error InvalidSalt()',
  'error MulDiv_Overflow()',
  'error NotAuthorized()',
  'error PoolMissing()',
  'error RevokeMoreThanIssued()',
  'error ShareClassNotFound()',
  'error Uint128_Overflow()',
  'error UnrecognizedFileParam()',
  'error ZeroApprovalAmount()',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index, string name, string symbol, bytes32 salt)',
  'event AddShareClass(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed index)',
  'event ApproveDeposits(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 assetId, uint128 approvedPoolAmount, uint128 approvedAssetAmount, uint128 pendingAssetAmount)',
  'event ApproveRedeems(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 assetId, uint128 approvedShareClassAmount, uint128 pendingShareClassAmount)',
  'event ClaimDeposit(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, bytes32 investor, uint128 assetId, uint128 approvedAssetAmount, uint128 pendingAssetAmount, uint128 claimedShareAmount)',
  'event ClaimRedeem(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, bytes32 investor, uint128 assetId, uint128 approvedShareClassAmount, uint128 pendingShareClassAmount, uint128 claimedAssetAmount)',
  'event Deny(address indexed user)',
  'event File(bytes32 what, address who)',
  'event IssueShares(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 nav, uint128 navPerShare, uint128 newTotalIssuance, uint128 issuedShareAmount)',
  'event NewEpoch(uint64 poolId, uint32 newIndex)',
  'event Rely(address indexed user)',
  'event RevokeShares(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint128 nav, uint128 navPerShare, uint128 newTotalIssuance, uint128 revokedShareAmount, uint128 revokedAssetAmount)',
  'event UpdateMetadata(uint64 indexed poolId, bytes16 indexed scId, string name, string symbol, bytes32 salt)',
  'event UpdateRequest(uint64 indexed poolId, bytes16 indexed scId, uint32 indexed epoch, uint8 requestType, bytes32 investor, uint128 assetId, uint128 pendingUserAmount, uint128 pendingTotalAmount, uint128 queuedAmount, bool pendingCancellation)',
  'event UpdateShareClass(uint64 indexed poolId, bytes16 indexed scId, uint128 nav, uint128 navPerShare, uint128 totalIssuance, bytes data)',
  'function addShareClass(uint64 poolId, string name, string symbol, bytes32 salt, bytes) returns (bytes16 scId_)',
  'function approveDeposits(uint64 poolId, bytes16 scId_, uint128 maxApproval, uint128 paymentAssetId, address valuation) returns (uint128 approvedAssetAmount, uint128 approvedPoolAmount)',
  'function approveRedeems(uint64 poolId, bytes16 scId_, uint128 maxApproval, uint128 payoutAssetId) returns (uint128 approvedShareAmount, uint128 pendingShareAmount)',
  'function cancelDepositRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) returns (uint128 cancelledAssetAmount)',
  'function cancelRedeemRequest(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 cancelledShareAmount)',
  'function claimDeposit(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId) returns (uint128 payoutShareAmount, uint128 paymentAssetAmount, uint128 cancelledAmount)',
  'function claimDepositUntilEpoch(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 depositAssetId, uint32 endEpochId) returns (uint128 payoutShareAmount, uint128 paymentAssetAmount, uint128 cancelledAssetAmount)',
  'function claimRedeem(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId) returns (uint128 payoutAssetAmount, uint128 paymentShareAmount, uint128 cancelledShareAmount)',
  'function claimRedeemUntilEpoch(uint64 poolId, bytes16 scId_, bytes32 investor, uint128 payoutAssetId, uint32 endEpochId) returns (uint128 payoutAssetAmount, uint128 paymentShareAmount, uint128 cancelledShareAmount)',
  'function decreaseShareClassIssuance(uint64 poolId, bytes16 scId_, uint128 navPerShare, uint128 amount)',
  'function deny(address user)',
  'function depositRequest(bytes16 scId, uint128 paymentAssetId, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function epochAmounts(bytes16 scId, uint128 assetId, uint32 epochId_) view returns (uint128 depositPending, uint128 depositApproved, uint128 depositPool, uint128 depositShares, uint128 redeemPending, uint128 redeemApproved, uint128 redeemAssets)',
  'function epochId(uint64 poolId) view returns (uint32)',
  'function epochPointers(bytes16 scId, uint128 assetId) view returns (uint32 latestDepositApproval, uint32 latestRedeemApproval, uint32 latestIssuance, uint32 latestRevocation)',
  'function exists(uint64 poolId, bytes16 scId_) view returns (bool)',
  'function file(bytes32 what, address data)',
  'function hubRegistry() view returns (address)',
  'function increaseShareClassIssuance(uint64 poolId, bytes16 scId_, uint128 navPerShare, uint128 amount)',
  'function issueShares(uint64 poolId, bytes16 scId_, uint128 depositAssetId, uint128 navPerShare)',
  'function issueSharesUntilEpoch(uint64 poolId, bytes16 scId_, uint128 depositAssetId, uint128 navPerShare, uint32 endEpochId)',
  'function metadata(bytes16 scId) view returns (string name, string symbol, bytes32 salt)',
  'function metrics(bytes16 scId) view returns (uint128 totalIssuance, uint128 navPerShare)',
  'function pendingDeposit(bytes16 scId, uint128 paymentAssetId) view returns (uint128 pending)',
  'function pendingRedeem(bytes16 scId, uint128 payoutAssetId) view returns (uint128 pending)',
  'function previewNextShareClassId(uint64 poolId) view returns (bytes16 scId)',
  'function previewShareClassId(uint64 poolId, uint32 index) pure returns (bytes16 scId)',
  'function queuedDepositRequest(bytes16 scId, uint128 paymentAssetId, bytes32 investor) view returns (bool isCancelling, uint128 amount)',
  'function queuedRedeemRequest(bytes16 scId, uint128 payoutAssetId, bytes32 investor) view returns (bool isCancelling, uint128 amount)',
  'function redeemRequest(bytes16 scId, uint128 payoutAssetId, bytes32 investor) view returns (uint128 pending, uint32 lastUpdate)',
  'function rely(address user)',
  'function requestDeposit(uint64 poolId, bytes16 scId_, uint128 amount, bytes32 investor, uint128 depositAssetId)',
  'function requestRedeem(uint64 poolId, bytes16 scId_, uint128 amount, bytes32 investor, uint128 payoutAssetId)',
  'function revokeShares(uint64 poolId, bytes16 scId_, uint128 payoutAssetId, uint128 navPerShare, address valuation) returns (uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'function revokeSharesUntilEpoch(uint64 poolId, bytes16 scId_, uint128 payoutAssetId, uint128 navPerShare, address valuation, uint32 endEpochId) returns (uint128 payoutAssetAmount, uint128 payoutPoolAmount)',
  'function salts(bytes32 salt) view returns (bool)',
  'function shareClassCount(uint64 poolId) view returns (uint32)',
  'function shareClassIds(uint64 poolId, bytes16) view returns (bool)',
  'function shareClassPrice(uint64 poolId, bytes16 scId_) view returns (uint128, uint128)',
  'function update(uint64, bytes) pure',
  'function updateMetadata(uint64 poolId, bytes16 scId_, string name, string symbol, bytes32 salt, bytes)',
  'function updateShareClass(uint64 poolId, bytes16 scId_, uint128 navPerShare, bytes data) returns (uint128, uint128)',
  'function wards(address) view returns (uint256)',
] as const
