export default [
  'error AssetMismatch()',
  'error AssetNotAllowed()',
  'error ExceedsMaxDeposit()',
  'error ExceedsMaxReserve()',
  'error FileUnrecognizedParam()',
  'error MulDiv_Overflow()',
  'error NoCode()',
  'error NotAuthorized()',
  'error SafeTransferEthFailed()',
  'error SafeTransferFailed()',
  'error ShareTokenDoesNotExist()',
  'error Uint128_Overflow()',
  'error UnknownMessageType()',
  'error UnknownUpdateContractType()',
  'error VaultAlreadyExists()',
  'error VaultDoesNotExist()',
  'event Deny(address indexed user)',
  'event File(bytes32 indexed what, address data)',
  'event Rely(address indexed user)',
  'event SetMaxReserve(uint64 indexed poolId, bytes16 indexed scId, address asset, uint256 tokenId, uint128 maxReserve)',
  'event SetValuation(uint64 indexed poolId, bytes16 indexed scId, address asset, uint256 tokenId, address oracle)',
  'function addVault(uint64 poolId, bytes16 scId, address vaultAddr, address asset_, uint128 assetId)',
  'function balanceSheet() view returns (address)',
  'function convertToAssets(address vaultAddr, uint256 shares) view returns (uint256 assets)',
  'function convertToShares(address vaultAddr, uint256 assets) view returns (uint256 shares)',
  'function deny(address user)',
  'function deposit(address vaultAddr, uint256 assets, address receiver, address owner) returns (uint256 shares)',
  'function escrow() view returns (address)',
  'function file(bytes32 what, address data)',
  'function maxDeposit(address, address) pure returns (uint256)',
  'function maxMint(address, address) pure returns (uint256)',
  'function maxReserve(uint64 poolId, bytes16 scId, address asset, uint256 tokenId) view returns (uint128)',
  'function mint(address vaultAddr, uint256 shares, address receiver, address owner) returns (uint256 assets)',
  'function poolManager() view returns (address)',
  'function previewDeposit(address vaultAddr, address, uint256 assets) view returns (uint256 shares)',
  'function previewMint(address vaultAddr, address, uint256 shares) view returns (uint256 assets)',
  'function priceAssetPerShare(uint64 poolId, bytes16 scId, uint128 assetId) view returns (uint128 price)',
  'function priceLastUpdated(address vaultAddr) view returns (uint64 lastUpdated)',
  'function prices(uint64 poolId, bytes16 scId, uint128 assetId, address asset, uint256 tokenId) view returns ((uint128 assetPerShare, uint128 poolPerAsset, uint128 poolPerShare) priceData)',
  'function recoverTokens(address token, address receiver, uint256 amount)',
  'function recoverTokens(address token, uint256 tokenId, address receiver, uint256 amount)',
  'function rely(address user)',
  'function removeVault(uint64 poolId, bytes16 scId, address vaultAddr, address asset_, uint128 assetId)',
  'function root() view returns (address)',
  'function setMaxReserve(uint64 poolId, bytes16 scId, address asset, uint256 tokenId, uint128 maxReserve_)',
  'function setValuation(uint64 poolId, bytes16 scId, address asset, uint256 tokenId, address valuation_)',
  'function update(uint64 poolId, bytes16 scId, bytes payload)',
  'function valuation(uint64 poolId, bytes16 scId, address asset, uint256 tokenId) view returns (address)',
  'function vault(uint64 poolId, bytes16 scId, uint128 assetId) view returns (address)',
  'function vaultByAssetId(uint64 poolId, bytes16 scId, uint128 assetId) view returns (address)',
  'function vaultKind(address vaultAddr) view returns (uint8, address)',
  'function wards(address) view returns (uint256)',
] as const
