export default [
  'error CallFailedWithEmptyRevert()',
  'error NoCode()',
  'error NotAuthorized()',
  'error SafeApproveFailed()',
  'error SafeTransferFailed()',
  'error SafeTransferFromFailed()',
  'error UnauthorizedSender()',
  'event Deny(address indexed user)',
  'event ExecuteLockedDepositRequest(address indexed vault, address indexed controller, address sender)',
  'event LockDepositRequest(address indexed vault, address indexed controller, address indexed owner, address sender, uint256 amount)',
  'event Rely(address indexed user)',
  'event UnlockDepositRequest(address indexed vault, address indexed controller, address indexed receiver)',
  'function cancelDepositRequest(address vault) payable',
  'function cancelRedeemRequest(address vault) payable',
  'function claimCancelDepositRequest(address vault, address receiver, address controller) payable',
  'function claimCancelRedeemRequest(address vault, address receiver, address controller) payable',
  'function claimDeposit(address vault, address receiver, address controller) payable',
  'function claimRedeem(address vault, address receiver, address controller) payable',
  'function deny(address user)',
  'function disable(address vault) payable',
  'function enable(address vault) payable',
  'function enableLockDepositRequest(address vault, uint256 amount) payable',
  'function escrow() view returns (address)',
  'function estimate(uint16 chainId, bytes payload) view returns (uint256 amount)',
  'function executeLockedDepositRequest(address vault, address controller) payable',
  'function gateway() view returns (address)',
  'function getVault(uint64 poolId, bytes16 scId, address asset) view returns (address)',
  'function hasPermissions(address vault, address controller) view returns (bool)',
  'function isEnabled(address vault, address controller) view returns (bool)',
  'function lockDepositRequest(address vault, uint256 amount, address controller, address owner) payable',
  'function lockedRequests(address controller, address vault) view returns (uint256 amount)',
  'function multicall(bytes[] data) payable',
  'function permit(address asset, address spender, uint256 assets, uint256 deadline, uint8 v, bytes32 r, bytes32 s) payable',
  'function poolManager() view returns (address)',
  'function recoverTokens(address token, uint256 tokenId, address to, uint256 amount)',
  'function registerAsset(address asset, uint256 tokenId, uint16 chainId) payable',
  'function rely(address user)',
  'function requestDeposit(address vault, uint256 amount, address controller, address owner) payable',
  'function requestRedeem(address vault, uint256 amount, address controller, address owner) payable',
  'function transferShares(address vault, uint16 chainId, address recipient, uint128 amount) payable',
  'function transferShares(address vault, uint16 chainId, bytes32 recipient, uint128 amount) payable',
  'function unlockDepositRequest(address vault, address receiver) payable',
  'function unwrap(address wrapper, uint256 amount, address receiver) payable',
  'function wards(address) view returns (uint256)',
  'function wrap(address wrapper, uint256 amount, address receiver, address owner) payable',
] as const
