name: Create Release
on:
  pull_request:
    types: [closed]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          chmod +x ./.github/ci-scripts/pr-label-check.sh
          
          # Capture both stdout and stderr from the script
          if ! RELEASE_TYPE=$(./.github/ci-scripts/pr-label-check.sh $PR_NUMBER 2>&1); then
            echo "::error::$RELEASE_TYPE"
            exit 1
          fi
          
          echo "::notice::Last PR merged detected: #$PR_NUMBER) with release label: $RELEASE_TYPE"

          if [ "$RELEASE_TYPE" = "minor" ] || [ "$RELEASE_TYPE" = "major" ] || [ "$RELEASE_TYPE" = "patch" ] || [ "$RELEASE_TYPE" = "alpha" ]; then
            VERSION=$(node -p "require('./package.json').version")
            gh release create "v${VERSION}" \
              --title "Release v${VERSION}" \
              --generate-notes \
              --target "${GITHUB_SHA}" \
              --prerelease
          elif [ "$RELEASE_TYPE" = "no-release" ]; then
            echo "::notice::PR is not flagged for release, skipping release creation"
          fi
