name: Trigger Docs update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Send Trigger to Repo B
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/organization/sdk-docs/dispatches \
          -d '{"event_type": "trigger-from-apps-repo"}'